### ISSUE TITLE
Travis CI build is failing

### ISSUE THREAD

**Issue by Krinkle** [zordius/lightncandy#307] opened 2019-04-02 18:36 UTC
There are currently two issues in the Travis CI build.

1.  PHP warning:
```
Undefined index: data in regressionTest.php:26
Undefined index: data in regressionTest.php:26
Undefined index: data in regressionTest.php:26
Undefined index: data in regressionTest.php:26
Undefined index: data in regressionTest.php:26
```

This fixed by https://github.com/zordius/lightncandy/pull/304.

2. PHPUnit assertion:

```
1) HandlebarsSpecTest::testSpecs with data set #292 (array('partials', 'partials with string context', 'Dudes: {{>dude "dudes"}}', array(), 'Dudes: dudes', array('{{.}}'), array(), 'specs/handlebars/spec/partials.json', 9, null))
Error: Class 'StringObject' not found
/tmp/lci_QHFRsI:76
/tmp/lci_QHFRsI:19
/tmp/lci_QHFRsI:187
/home/travis/build/zordius/lightncandy/tests/handlebarsSpecTest.php:300
```

**Comment by zordius** [comment] 2019-04-06 13:11
Similar patch is applied in https://github.com/zordius/lightncandy/commit/f872d882ce750a13da2ccfdc9af6b07d3a97f624#diff-57c6895bc9d5d022a2c0fa50f62c3306R28 and be merged into current master, the issue is fixed. So, close this. Thank you for your report!

**Closed by zordius** 2019-04-06 13:11 UTC
